### ISSUE TITLE
Cannot open assembly '/bin/CodeGenerator/Debug/CodeGenerator.exe': No such file or directory.

### ISSUE THREAD

**Issue by EcoEditor** [silentorbit/protobuf#54]
Hello

Started using ProtoBuf on a mac.
I'm using ProtoBuf with unity3D and usually would generate the c# script with "generate_state.command" file.
Got this issue when trying to do it on mac: 
**Cannot open assembly '/bin/CodeGenerator/Debug/CodeGenerator.exe': No such file or directory.**
The only solution was to type the following in a terminal:
export PROTO_BUF_PATH="/Users/<Username>/Documents/ProtoBuf
echo $PROTO_BUF_PATH
source ~/.bash_profile
cd mono $PROTO_BUF_PATH/bin/CodeGenerator/Debug/CodeGenerator.exe Assets/Scripts/ProtoBuf/<filename>.proto

What is the issue here? Why do I need to tell the path each time? How can it be solved?
Thank you.

**Comment by hultqvist** [comment]
The path '/bin/CodeGenerator/Debug/CodeGenerator.exe' does not look familiar.

Since CodeGenerator.exe is not installed you have to either place it in one of the searched locations or specify the full path as you did in your example.

I'm not familiar with mac environment but you should be able to get mor help in forums specific to mac.
They should be able to help you without specific knowledge about this project.
